jdbldDirectory = _jdbld

# Set to published snapshot during development of next version
# jdbldVersion = 0.6.1-SNAPSHOT

javaHome = /usr/lib/jvm/java-25

extensionsSnapshotRepository = \
    https://codeberg.org/api/packages/JDrupes/maven/
buildExtensions = \
    org.jdrupes:jdbld-ext-git:0.8.0
