jdbldDirectory = _jdbld

# Set to published snapshot during development of next version
jdbldVersion = 0.4.2-SNAPSHOT

javaHome = /usr/lib/jvm/java-25

extensionsRepositories = \
    https://repo1.maven.org/maven2/, \
    https://codeberg.org/api/packages/JDrupes/maven/
extensionsSnapshotRepository = \
    https://codeberg.org/api/packages/JDrupes/maven/
buildExtensions = \
    org.jdrupes:jdbld-ext-git:0.4.2-SNAPSHOT
