#!/usr/bin/bash

propertiesFile=".jdbld.properties"

if [ ! -r "$propertiesFile" ]; then
  cd `dirname $0`
fi

if [ ! -r "$propertiesFile" ]; then
  echo >&2 "File $propertiesFile must exist in root directory of build."
  exit 1
fi

getProperty() {
  cat "$propertiesFile" | while read line; do
    if expr match "$line" "^ *$1[ \t]*=" > /dev/null; then
      echo $line \
        | sed -E 's/^[[:space:]]*'$1'[[:space:]]*=[[:space:]]*(.*\S)[[:space:]]*$/\1/'
      return 1
    fi
  done
  if [ $? != 1 ]; then
    echo "$2"
  fi
}

jdbldDirectory=$(getProperty "jdbldDirectory" "_jdbld")

javaCmd=java
if [ -z "$JAVA_HOME" ]; then
  JAVA_HOME=$(getProperty "javaHome" "")
fi
if [ ! -z "$JAVA_HOME" ]; then
  javaCmd="$JAVA_HOME/bin/java"
fi

builderJar="$jdbldDirectory/app/jdrupes-builder-0.0.3-SNAPSHOT.jar"

if [ ! -r "$builderJar" ]; then
  echo >&2 "JDrupes Builder's executable jar not found."
  exit 1
fi

# Only for self build
cp "$builderJar" "$jdbldDirectory/app/jdrupes-builder-current.jar"
builderJar="$jdbldDirectory/app/jdrupes-builder-current.jar"

$javaCmd -Duser.language=en_US -jar "$builderJar" "$@"
