/*
 * JDrupes Builder
 * Copyright (C) 2025 Michael N. Lipp
 * 
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Affero General Public License as
 * published by the Free Software Foundation, either version 3 of the
 * License, or (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 * GNU Affero General Public License for more details.
 *
 * You should have received a copy of the GNU Affero General Public License
 * along with this program.  If not, see <https://www.gnu.org/licenses/>.
 */

package org.jdrupes.builder.java;

import org.jdrupes.builder.api.Cleaniness;
import org.jdrupes.builder.api.FileTree;
import org.jdrupes.builder.api.ResourceType;

/// Defines some constants for using the Java related components.
///
@SuppressWarnings("PMD.DataClass")
public class JavaConsts {

    /// The Java source files.
    public static final ResourceType<
            FileTree<JavaSourceFile>> JAVA_SOURCE_FILES = new ResourceType<>() {
            };

    /// The Java class files.
    public static final ResourceType<
            FileTree<ClassFile>> JAVA_CLASS_FILES = new ResourceType<>() {
            };

    /// The Java jar file.
    public static final ResourceType<JarFile> JAR_FILE
        = new ResourceType<>() {
        };

    /// The Java application jar file.
    public static final ResourceType<JarFile> APP_JAR_FILE
        = new ResourceType<>() {
        };

    /// The directory with files generated by javadoc.
    public static final ResourceType<JavadocDirectory> JAVADOC_DIRECTORY
        = new ResourceType<>() {
        };

    public static final ResourceType<Cleaniness> CLEANINESS
        = new ResourceType<>() {
        };
}
