/*
 * JDrupes Builder
 * Copyright (C) 2025 Michael N. Lipp
 * 
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Affero General Public License as
 * published by the Free Software Foundation, either version 3 of the
 * License, or (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 * GNU Affero General Public License for more details.
 *
 * You should have received a copy of the GNU Affero General Public License
 * along with this program.  If not, see <https://www.gnu.org/licenses/>.
 */

package org.jdrupes.builder.java;

import java.nio.file.Path;
import org.jdrupes.builder.api.FileResource;
import org.jdrupes.builder.api.Project;
import org.jdrupes.builder.api.ResourceFactory;
import org.jdrupes.builder.api.ResourceType;

/// A [FileResource] that represents a directory generated by javadoc.
///
public interface JavadocDirectory extends FileResource {

    /// Creates a new javadoc directory resource from the given
    /// project and path.
    ///
    /// @param project the project
    /// @param path the path relative to the project's directory (or an
    /// absolute path)
    /// @return the file resource
    ///
    static JavadocDirectory from(Project project, Path path) {
        return ResourceFactory.create(new ResourceType<>() {},
            project.directory().resolve(path));
    }
}
