source 'https://rubygems.org'
# gem 'github-pages', group: :jekyll_plugins
gem "jekyll", "~> 4.0"
gem "jekyll-seo-tag"
gem 'webrick', '~> 1.3', '>= 1.3.1'

gem "csv", "~> 3.3"

gem "base64", "~> 0.3.0"
