when:
- event: push
  evaluate: 'CI_SYSTEM_HOST == "woodpecker.mnl.de"'

clone:
- name: git
  image: woodpeckerci/plugin-git
  settings:
    partial: false
    tags: true
    depth: 0

steps:
- name: build-jars
  image: fedora
  commands:
    #- echo "[Adoptium]"  > /etc/yum.repos.d/adoptium.repo
    #- echo name=Adoptium >> /etc/yum.repos.d/adoptium.repo
    #- echo "baseurl=https://packages.adoptium.net/artifactory/rpm/${DISTRIBUTION_NAME:-$(. /etc/os-release; echo $ID)}/\$releasever/\$basearch" >-
    #    >> /etc/yum.repos.d/adoptium.repo
    #- echo enabled=1 >> /etc/yum.repos.d/adoptium.repo
    #- echo gpgcheck=1 >> /etc/yum.repos.d/adoptium.repo
    #- echo gpgkey=https://packages.adoptium.net/artifactory/api/gpg/key/public >> /etc/yum.repos.d/adoptium.repo
    #- cat /etc/yum.repos.d/adoptium.repo
    - dnf install -y graphviz java-25-openjdk-devel xmlstarlet
    - /usr/lib/jvm/java-25-openjdk/bin/javac
    - JAVA_HOME=/usr/lib/jvm/java-25-openjdk ./jdbld -B-x 'test-*-project' -B-x 'test-projects/*project*' build
 